@GymManagement_HostAddress = http://localhost:5017

GET {{GymManagement_HostAddress}}/health
Accept: application/json

###

GET {{GymManagement_HostAddress}}/weatherforecast/
Accept: application/json

###

