# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - tfi-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build with dotnet
        run: dotnet build src/GymManagement.slnx --configuration Release

      - name: dotnet publish
        run: dotnet publish src/GymManagement/GymManagement.Presentation.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_665DA86E562443F5A7E87501123D82CE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_468EB11C28B448FB8DF2FF314F765611 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2058794F4CF84A6B915E1403D4448495 }}

      - name: Install dotnet-ef tools
        run: dotnet tool install --global dotnet-ef

      - name: Run EF Core migrations
        run: dotnet ef database update --project Infraestructure/GymManagement.Infrastructure.csproj --startup-project GymManagement/GymManagement.Presentation.csproj --connection "${{ secrets.DB_CONNECTION_STRING }}"
        env:
          ASPNETCORE_ENVIRONMENT: Production
          ConnectionStrings__GymManagementConnectionString: ${{ secrets.DB_CONNECTION_STRING }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tfi-api'
          slot-name: 'Production'
          package: .